apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
    name: dsw-install
spec:
    params:
        - name: default-step-image
          type: string
          description: Image to use to execute step
          default: "image-registry.openshift-image-registry.svc:5000/techzone-test/dsw-tekton-base:0.0.2"
        - name: keycloak-dsw-realm-name
          type: string
          description: "Name of keycloak realm to authenticate DSW against"
          default: "dsw"
        - name: devops-model-chart-repo
          type: string
          description: "URL of helm repo providing the DSW helm chart"
          default: "https://raw.githubusercontent.com/knowis/dsw-install-pipeline/refs/heads/main/ibm-devops-model"
        - name: devops-model-chart-version
          type: string
          description: "DSW chart version to use"
          default: "5.1.1"
    workspaces:
        - name: global-wksp
    tasks:
        - name: bootstrap
          params:
              - name: default-step-image
                value: "$(params.default-step-image)"
          workspaces:
              - name: shared-wksp
                workspace: global-wksp
          taskSpec:
              displayName: bootstrap
              description: "Task to determine some global facts required by multiple tasks in the pipeline"
              workspaces:
                - name: shared-wksp
                  description: |
                    Folder to read and write files to that are shared amongst tasks in the parent pipeline
              params:
                - name: default-step-image
                  type: string
                  description: Image to use to execute step
              results:
                  - name: cluster-app-url
                    description: "Url (suffix) for services exposed by the cluster"
              steps:
                - name: determine-cluster-app-host
                  image: "$(params.default-step-image)"
                  script: |
                    #!/usr/bin/bash
                    set -e

                    echo "Createing dummy route to extract apps url from"
                    SVC_NAME="dummy-route-$(tr -dc 'a-z0-9' < /dev/random | head -c 5)"
                    oc create route edge --service=$SVC_NAME --port=34567
                    oc get route $SVC_NAME -o jsonpath='{.spec.host}'|sed -nE 's/^.*\.(apps\..*$)/\1/p' | tee $(results.cluster-app-url.path)

                    oc delete route $SVC_NAME

                    echo "Deleted dummy route $SVC_NAME again"
        - name: install-keycloak
          params:
              - name: default-step-image
                value: "$(params.default-step-image)"
              - name: keycloak-dsw-realm-name
                value: "$(params.keycloak-dsw-realm-name)"
          taskRef:
              name: install-keycloak
          workspaces:
              - name: shared-wksp
                workspace: global-wksp
          runAfter:
              - bootstrap
        - name: create-mandatory-config
          params:
              - name: default-step-image
                value: "$(params.default-step-image)"
              - name: cluster-app-url
                value: "$(tasks.bootstrap.results.cluster-app-url)"
              - name: keycloak-dsw-realm-name
                value: "$(params.keycloak-dsw-realm-name)"
              - name: keycloak-credentials-secret
                value: "$(tasks.install-keycloak.results.keycloak-credentials-secret)"
              - name: keycloak-url
                value: "$(tasks.install-keycloak.results.keycloak-url)"
          taskRef:
              name: create-mandatory-config
          workspaces:
              - name: shared-wksp
                workspace: global-wksp
        - name: install-dsw
          params:
              - name: default-step-image
                value: "$(params.default-step-image)"
              - name: cluster-app-url
                value: "$(tasks.bootstrap.results.cluster-app-url)"
              - name: keycloak-dsw-realm-name
                value: "$(params.keycloak-dsw-realm-name)"
              - name: keycloak-credentials-secret
                value: "$(tasks.install-keycloak.results.keycloak-credentials-secret)"
              - name: keycloak-url
                value: "$(tasks.install-keycloak.results.keycloak-url)"
              - name: devops-model-chart-repo
                value: "$(params.devops-model-chart-repo)"
              - name: devops-model-chart-version
                value: "$(params.devops-model-chart-version)"
          taskRef:
              name: install-dsw
          workspaces:
              - name: shared-wksp
                workspace: global-wksp
