apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: install-keycloak
spec:
  workspaces:
    - name: shared-wksp
      description: |
        Folder to read and write files to that are shared amongst tasks in the parent pipeline
  params:
    - name: postgres-chart-name
      type: string
      description: Fully qualified repo url of chart, e.g. oci://registry-1.docker.io/cloudpirates/postgres
      default: "oci://registry-1.docker.io/cloudpirates/postgres"
    - name: postgres-release-name
      type: string
      description: The name of the Helm release
      default: "keycloak-postgres"
    - name: postgres-chart-version
      type: string
      description: The version of the Helm chart
      default: "0.13.8"
    - name: keycloak-chart-name
      type: string
      description: Fully qualified repo url of chart, e.g. oci://registry-1.docker.io/cloudpirates/keycloak
      default: "oci://registry-1.docker.io/cloudpirates/keycloak"
    - name: keycloak-release-name
      type: string
      description: The name of the Helm release
      default: "dsw-auth"
    - name: keycloak-chart-version
      type: string
      description: The version of the Helm chart
      default: "0.11.4"
    - name: postgres-set-values
      type: string
      description: "Optional list of key value pairs specified like this: key=value"
      default: "auth.existingSecret=keycloak-postgres-postgres-credentials,auth.secretKeys.adminPasswordKey=postgres-password,customUser.existingSecret=keycloak-postgres-keycloak-user-credentials,customUser.secretKeys.name=username,customUser.secretKeys.database=database,customUser.secretKeys.password=password"
    - name: default-step-image
      type: string
      description: Image to use to execute step
    - name: keycloak-dsw-realm-name
      type: string
      description: "Name of realm in keycloak to be used for authenticating to DSW"
      default: "dsw"
  results:
    - name: keycloak-url
      description: "Url for keycloak admin web (without protocol)"
    - name: keycloak-credentials-secret
      description: "Name of secret containining credentials for keycloak admin user"
    - name: postgres-credentials-secret
      description: "Name of secret containing credentials for postgres admin user"
    - name: postgres-service-url
      description: "Name of service providing postgress access"
  steps:
    - name: create-postgres-secrets
      image: "$(params.default-step-image)"
      script: |
        #!/usr/bin/bash
        set -e

        echo "Starting generation of keycloak postgres secrets"

        # Create secret 'keycloak-postgres-postgres-credentials' if it doesn't exist yet
        if [ -z "$(oc get secret keycloak-postgres-postgres-credentials --ignore-not-found)" ]; then
          echo "Creating secret 'keycloak-postgres-postgres-credentials'"
          postgres_password=$(tr -dc 'A-Za-z0-9!?%=+_&;%§#-' < /dev/random | head -c 15)
          oc create secret generic keycloak-postgres-postgres-credentials --from-literal=postgres-password="${postgres_password}"
        else
          echo "Secret 'keycloak-postgres-postgres-credentials' already exists. Skipping…"
        fi

        echo "keycloak-postgres-postgres-credentials" | tee $(results.postgres-credentials-secret.path)

        # Create secret 'keycloak-postgres-keycloak-user-credentials' if it doesn't exist yet
        if [ -z "$(oc get secret keycloak-postgres-keycloak-user-credentials --ignore-not-found)" ]; then
          echo "Creating secret 'keycloak-postgres-keycloak-user-credentials'"
          keycloak_user_password=$(tr -dc 'A-Za-z0-9!?%=+_&;%§#-' < /dev/random | head -c 15)
          oc create secret generic keycloak-postgres-keycloak-user-credentials --from-literal=username=keycloak --from-literal=database=keycloak --from-literal=password="${keycloak_user_password}"
        else
          echo "Secret 'keycloak-postgres-keycloak-user-credentials' already exists. Skipping…"
        fi


    - name: install-postgres
      image: "$(params.default-step-image)"
      script: |
        #!/usr/bin/bash
        set -e

        echo "Starting Helm installation..."

        # Build helm install command
        HELM_CMD="helm install $(params.postgres-release-name) $(params.postgres-chart-name)"

        # Add version if specified
        if [ -n "$(params.postgres-chart-version)" ]; then
          HELM_CMD="$HELM_CMD --version $(params.postgres-chart-version)"
        fi

        # Add set values if specified
        if [ -n "$(params.postgres-set-values)" ]; then
          HELM_CMD="$HELM_CMD --set $(params.postgres-set-values)"
        fi

        # Execute helm install
        echo "Executing: $HELM_CMD"
        eval $HELM_CMD

        # build service string
        PGNS=$(oc get service $(params.postgres-release-name) -o jsonpath='{.metadata.namespace}')
        echo "$(params.postgres-release-name).${PGNS}.svc.cluster.local" | tee $(results.postgres-service-url.path)

        echo "Helm installation completed successfully!"
      env:
        - name: HOME
          value: /tmp

    - name: create-keycloak-secret
      image: "$(params.default-step-image)"
      script: |
        #!/usr/bin/bash
        set -e

        echo "Starting generation of keycloak secret"

        # Create secret 'keycloak-credentials' if it doesn't exist yet
        KC_CRED_SECRET="keycloak-credentials"
        if [ -z "$(oc get secret $KC_CRED_SECRET --ignore-not-found)" ]; then
          echo "Creating secret $KC_CRED_SECRET"
          admin_password=$(tr -dc 'A-Za-z0-9!?%=+_&;%§#-' < /dev/random | head -c 15)
          oc create secret generic $KC_CRED_SECRET --from-literal=admin-password="${admin_password}"
        else
          echo "Secret $KC_CRED_SECRET already exists. Skipping…"
        fi

        echo $KC_CRED_SECRET > $(results.keycloak-credentials-secret.path)

    - name: install-keycloak-chart
      image: "$(params.default-step-image)"
      script: |
        #!/usr/bin/bash
        set -e

        echo "Starting Helm installation of keycloak..."
        active_project="$(oc get secret keycloak-postgres-keycloak-user-credentials -o jsonpath="{.metadata.namespace}")"
        echo "Assuming current namespace is $active_project"

        # Build helm install command
        HELM_CMD="helm install $(params.keycloak-release-name) $(params.keycloak-chart-name)"

        # Add version if specified
        if [ -n "$(params.keycloak-chart-version)" ]; then
          HELM_CMD="$HELM_CMD --version $(params.keycloak-chart-version)"
        fi

        # Execute helm install
        echo "Executing: $HELM_CMD"
        eval '$HELM_CMD --values - << EOF
        # values-external-secret.yaml
        keycloak:
          existingSecret: "keycloak-credentials"
          secretKeys:
            adminPasswordKey: "admin-password"
          production: true
          proxyHeaders: "xforwarded"

        database:
          type: "postgres"
          host: "$(params.postgres-release-name).${active_project}.svc.cluster.local"
          name: "keycloak"
          existingSecret: "keycloak-postgres-keycloak-user-credentials"
          secretKeys:
            passwordKey: "password"
            usernameKey: "username"

        # Disable embedded databases
        postgres:
          enabled: false
        mariadb:
          enabled: false

        # Create dsw realm
        realm:
          import: true
          configFile: |
            {
              "realm": "$(params.keycloak-dsw-realm-name)",
              "enabled": true
            }

        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        EOF'

    - name: create-keycloak-route
      image: "$(params.default-step-image)"
      script: |
        #!/usr/bin/bash
        set -e

        echo "Createing keycloak route"
        oc create route edge dsw-auth --service="$(params.keycloak-release-name)-keycloak" --port=8080

        oc get route dsw-auth -o jsonpath='{.spec.host}' | tee $(results.keycloak-url.path)

    - name: wksp-test
      image: "$(params.default-step-image)"
      script: |
        #!/usr/bin/bash
        set -e

        if [ "$(workspaces.shared-wksp.bound)" == "true" ] ; then
          echo "Sharing info via $(workspaces.shared-wksp.path)/message"
          ls -al $(workspaces.shared-wksp.path)
          cat $(workspaces.shared-wksp.path)/message
          echo "hello from keycloak-install!" >> $(workspaces.shared-wksp.path)/message
          cat $(workspaces.shared-wksp.path)/message | echo -
        else
          echo "Workspace shared-wksp not bound"
        fi
