apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-gitlab
spec:
  params:
    - name: default-step-image
      type: string
      description: Image to use to execute step
    - name: install-namespace
      type: string
      description: "Namespace to install into"
      default:
    - name: operator-name
      type: string
      description: "Name of the GitLab operator"
      default: gitlab-operator-kubernetes
    - name: cluster-app-url
      type: string
      description: The cluster host needed to construct routes/ingresses in the form of apps.yourcloster.tld
    - name: gitlab-helm-chart-version
      type: string
      description: "Version of the helm chart that the operator should install. Needs to be compatible with the operator version."
      default: 9.8.2
    - name: keycloak-dsw-realm-name
      type: string
      description: "Name of realm in keycloak to be used for authenticating to DSW"
      default: "dsw"
    - name: keycloak-credentials-secret
      type: string
      description: "Name of the secret holding the admin credentials for keycloak"
      default: "keycloak-credentials"
    - name: keycloak-url
      type: string
      description: "Url of keycloak admin host (without protocol)"
    - name: instance-prefix
      type: string
      description: "Prefix to use for all gitlab subdomains"
      default: dsw
  results:
    - name: release-status
      description: "The status of the Helm release"
  steps:
    - name: create-oauth-secret
      image: "$(params.default-step-image)"
      script: |
        #!/usr/bin/bash
        set -e

        NS_INST=$(params.install-namespace)
        KC_URL=$(params.keycloak-url)
        KC_REALM=$(params.keycloak-dsw-realm-name)
        APP_URL=$(params.cluster-app-url)
        GL_PREFIX=$(params.instance-prefix)
        GL_CLIENT=gitlab
        KC_CRED_SECRET=$(params.keycloak-credentials-secret)

        echo "Reading keycloak credentials from secret $KC_CRED_SECRET in namespace $NS_INST"
        KC_ADMIN_PW="$(oc get secret $KC_CRED_SECRET -o jsonpath='{.data.admin-password}' -n $NS_INST|base64 -d)"

        echo "Creating keycloak client for GitLab in realm $KC_REALM"

        TOKEN=$(curl --silent --location --request POST "https://$KC_URL/realms/master/protocol/openid-connect/token" \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode 'client_id=admin-cli' \
          --data-urlencode 'grant_type=password' \
          --data-urlencode 'username=admin' \
          --data-urlencode "password=$KC_ADMIN_PW" | jq -r '.access_token')

        echo "Successfully fetched keycloak admin token"

        echo "calling https://$KC_URL/admin/realms/$KC_REALM/clients"

        curl -v  --request POST \
          --url https://$KC_URL/admin/realms/$KC_REALM/clients \
          --header 'content-type: application/json' \
          --header "Authorization: Bearer $TOKEN" \
          --data "{
          \"protocol\": \"openid-connect\",
          \"clientId\": \"$GL_CLIENT\",
          \"enabled\": true,
          \"publicClient\": false,
          \"standardFlowEnabled\": true,
          \"serviceAccountsEnabled\": false,
          \"directAccessGrantsEnabled\": true,
          \"rootUrl\": \"https://$GL_PREFIX-gitlab.$APP_URL\",
          \"redirectUris\": [
            \"https://$GL_PREFIX-gitlab.$APP_URL/*\"
          ]
        }"

        echo "Successfully created gitlab client in realm $KC_REALM"

        # KCC_SECRET=$(curl --silent --request GET \
        #   --url https://$KC_URL/admin/realms/$KC_REALM/clients/$CLIENT_ID \
        #   --header "Authorization: Bearer $TOKEN" | jq -r '.secret')

        # echo "Creating secret keycloak-oauth2 to configure openid for GitLab"

        # oc create -f - << EOF
        # kind: Secret
        # apiVersion: v1
        # metadata:
        #   name: keycloak-oauth2
        #   namespace: $NS_INST
        # stringData:
        #   provider: |
        #     name: "openid_connect"
        #     label: "Keycloak"
        #     args:
        #       name: "openid_connect"
        #       scope: ["openid", "profile", "email"]
        #       response_type: "code"
        #       issuer:  "https://$KC_URL/realms/$KC_REALM"
        #       client_auth_method: "query"
        #       discovery: true
        #       uid_field: "preferred_username"
        #       pkce: true
        #       client_options:
        #         identifier: "gitlab"
        #         secret: "$KCC_SECRET"
        #         redirect_uri: "https://$GL_PREFIX-gitlab.$APP_URL/users/auth/openid_connect/callback"
        # EOF

        # echo "Secret keycloak-oauth2 created"
