apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-helm-install
spec:
  params:
    - name: chart-name
      type: string
      description: Fully qualified repo url of chart, e.g. oci://registry-1.docker.io/cloudpirates/mongodb
      default: ""
    - name: release-name
      type: string
      description: The name of the Helm release
      default: "my-release"
    - name: chart-version
      type: string
      description: The version of the Helm chart
      default: ""
    - name: namespace
      type: string
      description: The Kubernetes namespace to install into
      default: "default"
    - name: set-values
      type: string
      description: Optional comma-separated key=value pairs to set
      default: ""
  results:
    - name: release-status
      description: "The status of the Helm release"
  steps:
    - name: helm-install
      image: image-registry.openshift-image-registry.svc:5000/techzone-test/dsw-tekton-base:0.0.2
      script: |
        #!/usr/bin/bash
        set -e

        echo "Starting Helm installation..."

        # Build helm install command
        HELM_CMD="helm install $(params.release-name) $(params.chart-name) --namespace $(params.namespace)"

        # Add version if specified
        if [ -n "$(params.chart-version)" ]; then
          HELM_CMD="$HELM_CMD --version $(params.chart-version)"
        fi

        # Add set values if specified
        if [ -n "$(params.set-values)" ]; then
          HELM_CMD="$HELM_CMD --set $(params.set-values)"
        fi

        # Execute helm install
        echo "Executing: $HELM_CMD"
        eval $HELM_CMD

        # Get release status
        helm status $(params.release-name) -n $(params.namespace) | tee $(results.release-status.path)

        echo "Helm installation completed successfully!"
      env:
        - name: HOME
          value: /tmp
